### PR TITLE
Add creation of `rsyncd.conf` to `adb-start-rsyncd.sh`

### PR DESCRIPTION
**Pull request by tukusejssirs**
- By creating `rsyncd.conf` in `adb-start-rsyncd.sh`, one can simply run `curl -o- https://raw.githubusercontent.com/JBBgameich/rsync-static/master/adb-start-rsyncd.sh | bash` in order to run the script without either cloning the whole repo or downloading two separate files.

- I also added a note to README.md about this.

### CODE REVIEW

**Comment by jbruechert** [comment]
Please rebase the branch on the updated master branch.

**Comment by tukusejssirs** [comment]
It should be okay now.

Anyway, do you know why Travic CI fails while building? It fails running `sudo apt-get update`; here’s the log:

```bash
$ sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://apt.postgresql.org/pub/repos/apt xenial-pgdg InRelease [56.4 kB]
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:6 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main amd64 Packages [209 kB]
Get:7 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main i386 Packages [209 kB]
Ign:7 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main i386 Packages
Get:7 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main i386 Packages [115 kB]
Ign:7 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main i386 Packages
Get:7 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main i386 Packages [787 kB]
Err:7 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main i386 Packages
  Writing more data than expected (788347 > 787357)
Fetched 109 kB in 0s (263 kB/s)
Reading package lists... Done
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/xenial-pgdg/main/binary-i386/Packages  Writing more data than expected (788347 > 787357)
E: Some index files failed to download. They have been ignored, or old ones used instead.

The command "sudo apt-get update" failed and exited with 100 during .
```

I believe you don’t need `psql`, so why is it loading that `apt` repo/PPA?

**Comment by jbruechert** [comment]
That is included in travis default image unfortunately. Let's ignore the ci failure for now since you didn't touch the compilation scripts.

**Comment by tukusejssirs** [comment]
It might be connected with the fact that Travis CI uses Ubuntu 16.04.6 LTS (Xenial Xerus) and the repos/PPAs are quite old, probably unmaintained or even deleted.

It _might_ be fixed by using the latest Ubuntu version supported by Travis CI, which is currently Ubuntu 18.04 ([src](https://docs.travis-ci.com/user/reference/bionic/)).

**Comment by jbruechert** [comment]
Seems like all travis xenial jobs don't work right now, I guess this will be fixed soon by travis ci.

**Comment by jbruechert** [comment]
Just noticed it seems to be back to normal already

**Pull request merged**
